import { nanoid } from 'nanoid';

export const abstracts = [
  {
    id: nanoid(),
    title: 'Transitional realms',
    path: 'abstract-art',
    type: 'Digital Abstract Art',
    cover: '/images/ABSTRACTS/1/TransitionalRealms/transitionalrealms.png',
    wips: [
      '/images/ABSTRACTS/1/TransitionalRealms/TRRed.png',
      '/images/ABSTRACTS/1/TransitionalRealms/TRBlue.png',
      '/images/ABSTRACTS/1/TransitionalRealms/TROrange.png',
      '/images/ABSTRACTS/1/TransitionalRealms/TRPink.png',
      '/images/ABSTRACTS/1/TransitionalRealms/TRYellow.png',
    ],
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1409,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Painted sun in abstract',
    path: 'abstract-art',
    type: 'Digital Abstract Art',
    cover: '/images/ABSTRACTS/1/PaintedSunInAbstract/PaintedSunInAbstract.png',
    wips: [
      '/images/ABSTRACTS/1/PaintedSunInAbstract/PaintedSunInAbstractBlue.png',
      '/images/ABSTRACTS/1/PaintedSunInAbstract/PaintedSunInAbstractOrange.png',
      '/images/ABSTRACTS/1/PaintedSunInAbstract/PaintedSunInAbstractPurple.png',
      '/images/ABSTRACTS/1/PaintedSunInAbstract/PaintedSunInAbstractRed.png',
      '/images/ABSTRACTS/1/PaintedSunInAbstract/PaintedSunInAbstractYellow.png',
    ],
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1442,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Comissioned Abstract Work 1',
    path: 'abstract-art',
    type: 'Abstract Work',
    cover: '/images/ABSTRACTS/1/Patrick/01-render.png',
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    path: 'abstract-art',
    title: 'Comissioned Abstract Work 2',
    type: 'Abstract Work',
    cover: '/images/ABSTRACTS/1/Patrick/02-render.png',
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    path: 'abstract-art',
    title: 'Comissioned Abstract Work 3',
    type: 'Commissioned Abstract Work',
    cover: '/images/ABSTRACTS/1/Patrick/03-render.png',
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    path: 'abstract-art',
    title: 'Perpetual Shatterings of Reality in Dashes of Color',
    type: 'Digital Abstract Art',
    cover: '/images/ABSTRACTS/1/PSoRiDoC/PSoRiDoC.png',
    wips: [
      '/images/ABSTRACTS/1/PSoRiDoC/PSoRiDoBaW.png',
      '/images/ABSTRACTS/1/PSoRiDoC/PSoRiDoBlue.png',
      '/images/ABSTRACTS/1/PSoRiDoC/PSoRiDoOrange.png',
      '/images/ABSTRACTS/1/PSoRiDoC/PSoRiDoPurple.png',
      '/images/ABSTRACTS/1/PSoRiDoC/PSoRiDoRed.png',
      '/images/ABSTRACTS/1/PSoRiDoC/PSoRiDoYellow.png',
    ],
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Streams of Alchemy',
    path: 'abstract-art',
    type: 'Digital Abstract Art',
    cover: '/images/ABSTRACTS/1/StreamsOfAlchemy/streamsofalchemy.png',
    wips: ['/ABSTRACTS/1/StreamsOfAlchemy/streamsofalchemyblackwhite.png'],
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Untitled 1',
    path: 'abstract-art',
    type: 'Digital Abstract Art',
    cover: '/images/ABSTRACTS/2/1/1.png',
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1448,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Untitled 2',
    path: 'abstract-art',
    type: 'Digital Abstract Art',
    cover: '/images/ABSTRACTS/2/2/2.png',
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1448,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Untitled 3',
    path: 'abstract-art',
    type: 'Digital Abstract Art',
    cover: '/images/ABSTRACTS/2/3/3.png',
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1448,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Untitled 4',
    path: 'abstract-art',
    type: 'Digital Abstract Art',
    cover: '/images/ABSTRACTS/2/4/4.png',
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Untitled 5',
    path: 'abstract-art',
    type: 'Digital Abstract Art',
    cover: '/images/ABSTRACTS/2/5/5.png',
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Untitled 6',
    path: 'abstract-art',
    type: 'Digital Abstract Art',
    cover: '/images/ABSTRACTS/2/6/6.png',
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Untitled 7',
    path: 'abstract-art',
    type: 'Digital Abstract Art',
    cover: '/images/ABSTRACTS/2/7/7.png',
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Untitled 8',
    path: 'abstract-art',
    type: 'Digital Abstract Art',
    cover: '/images/ABSTRACTS/2/8/8.png',
    coveralt: 'Digital abstract render made with Blender',
    description: `3D abstract art made with Blender.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
];
