import { nanoid } from 'nanoid';

export const gameart = [
  {
    id: nanoid(),
    title: 'Lowpoly Kitchen Assets',
    path: 'kitchen-assets',
    type: 'Kitchen Assets',
    cover: '/images/GAMEART/Kitchen Assets/all.png',
    wips: [
      '/GAMEART/Kitchen Assets/ed-1.png',
      '/GAMEART/Kitchen Assets/ed-2.png',
      '/GAMEART/Kitchen Assets/ed-3.png',
      '/GAMEART/Kitchen Assets/ed-4.png',
      '/GAMEART/Kitchen Assets/ed-5.png',
      '/GAMEART/Kitchen Assets/batedeira_shadeless.png',
      '/GAMEART/Kitchen Assets/blender.png',
      '/GAMEART/Kitchen Assets/viewport.png',
    ],
    coveralt: 'A collection of colorful lowpoly kitchen assets.',
    description: `A collection of colorful lowpoly kitchen assets.`,
    width: 2250,
    height: 1125,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Stylized Waterwell',
    path: 'waterwell',
    type: 'Stylized Waterwell',
    cover: '/images/GAMEART/Waterwell/waterwell.png',
    coveralt: 'A stylized waterwell 3D model',
    description: `Study of a stylized waterwell.`,
    width: 1080,
    height: 1080,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Lowpoly Ambulance',
    path: 'ambulance',
    type: 'Lowpoly Vehicle',
    cover: '/images/GAMEART/Ambulance/ambulance.png',
    wips: [
      '/GAMEART/Ambulance/ambulance.gif',
      '/GAMEART/Ambulance/wip_ambulance (1).png',
      '/GAMEART/Ambulance/wip_ambulance (2).png',
      '/GAMEART/Ambulance/wip_ambulance (3).png',
    ],
    coveralt: 'A 3D model of an ambulance',
    description: `3D lowpoly asset.`,
    width: 1052,
    height: 744,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Lowpoly Taxi',
    path: 'taxi',
    type: 'Lowpoly Vehicle',
    cover: '/images/GAMEART/Taxi/taxi.png',
    wips: [
      '/GAMEART/Taxi/taxi_side (1).png',
      '/GAMEART/Taxi/taxi_side (2).png',
      '/GAMEART/Taxi/taxigif.gif',
    ],
    coveralt: 'A 3D model of a taxi',
    description: `3D lowpoly vehicle asset.`,
    width: 1052,
    height: 744,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Lowpoly Submarine',
    path: 'submarine',
    type: 'Lowpoly Submarine',
    cover: '/images/GAMEART/Submarine/submarino5.png',
    wips: [
      '/GAMEART/Submarine/gifsub1.png',
      '/GAMEART/Submarine/gifsub2.png',
      '/GAMEART/Submarine/gifsub3.png',
      '/GAMEART/Submarine/gifsub4.png',
      '/GAMEART/Submarine/gifsub5.png',
      '/GAMEART/Submarine/gifsub6.png',
    ],
    coveralt: 'A 3D model of an submarine',
    description: `3D lowpoly asset.`,
    width: 1920,
    height: 1080,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    path: 'the-joker',
    type: 'Lowpoly Joker',
    cover: '/images/GAMEART/Joker/joker.png',
    title: 'Lowpoly Joker',
    coveralt: 'A 3D lowpoly model of The Joker',
    description: `3D lowpoly character based on The Joker.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Lighthouse',
    path: 'lighthouse',
    type: 'Sculpting and texturing study',
    cover: '/images/GAMEART/Lighthouse Study/lighthouse.png',
    wips: [
      '/GAMEART/Lighthouse Study/lighthouse-door.png',
      '/GAMEART/Lighthouse Study/lighthouse-shed.png',
    ],
    coveralt: 'Lighthouse and shed',
    description: `Personal sculpting and texturing study with Blender.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Lowpoly Ambulance',
    path: 'the-oddinn',
    type: 'GameJam Assets',
    cover: '/images/GAMEART/The OddInn/inn.png',
    wips: ['/GAMEART/The OddInn/vikings.png', '/GAMEART/The OddInn/goblin.png'],
    coveralt: 'A medieval inn',
    description: `Assets for The OddInn.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Stylized Sculpted Rocks',
    path: 'stylized-rock-studies',
    type: 'Stylized Rocks',
    cover: '/images/GAMEART/Stylized Rock Studies/stylizedrock (2).png',
    wips: [
      '/GAMEART/Stylized Rock Studies/stylizedrock (3).png',
      '/GAMEART/Stylized Rock Studies/stylizedrock (1).png',
    ],
    coveralt: 'A medieval inn',
    description: `Assets for The OddInn.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Lowpoly Character 1',
    path: 'lowpoly-character-study',
    type: 'Lowpoly Character Study',
    cover: '/images/GAMEART/Lowpoly Character Study 1/lowpolycharacter.png',

    coveralt: 'Lighthouse and shed',
    description: `sculpting and texturing study with Blender.`,
    width: 1800,
    height: 840,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Lowpoly Character 2',
    path: 'lowpoly-character-study-2',
    type: 'Lowpoly Character Study',
    cover: '/images/GAMEART/Lowpoly Character Study 2/Lowpoly Character 2.png',
    wips: [
      '/GAMEART/Lowpoly Character Study 2/Lowpoly Character 2-2.png',
      '/GAMEART/Lowpoly Character Study 2/Lowpoly Character 2-3.png',
    ],
    coveralt: 'Colorful lowpoly character',
    description: `Lowpoly colorful 3D character.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Lowpoly Character 3',
    path: 'lowpoly-character-study-3',
    type: 'Lowpoly Character Study',
    cover: '/images/GAMEART/Lowpoly Character Study 3/lowpolycharacter3.png',
    coveralt: 'Lowpoly character',
    description: `Lowpoly 3D character.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
];
