import { nanoid } from 'nanoid';

export const illustrations = [
  {
    id: nanoid(),
    title: 'Like a Cannonball',
    path: 'like-a-cannonball',
    type: 'Album Cover Artwork',
    cover: '/images/ILLUSTRATIONS/ALBIN/likeacannonball.png',
    wips: [
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/1.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/2.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/3.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/4.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/5.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/6.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/7.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/8.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/9.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/10.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/11.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/12.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/13.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/14.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/15.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/16.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/17.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/18.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/19.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/20.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/21.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/22.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/23.png',
      '/images/ILLUSTRATIONS/ALBIN/LACB_WIP/24.png',
    ],
    coveralt: 'Cover artwork for Albin\'s "Like A Cannonball"',
    description: `Digital illustration for Albin's music single "Like A Cannonball".`,
    width: 1024,
    height: 1024,
    tools: [
      'Blender 3D',
      'Substance Designer',
      'Substance Painter',
      'Adobe Photoshop',
    ],
  },
  {
    id: nanoid(),
    title: 'Love in Slow Motion',
    path: 'love-in-slow-motion',
    type: 'Album Cover Artwork',
    cover: '/images/ILLUSTRATIONS/ALBIN/loveinslowmotion.png',
    wips: [
      '/ALBIN/LISM_WIP/1.png',
      '/ALBIN/LISM_WIP/2.png',
      '/ALBIN/LISM_WIP/3.png',
      '/ALBIN/LISM_WIP/4.png',
      '/ALBIN/LISM_WIP/5.png',
      '/ALBIN/LISM_WIP/6.png',
      '/ALBIN/LISM_WIP/7.png',
      '/ALBIN/LISM_WIP/8.png',
      '/ALBIN/LISM_WIP/9.png',
      '/ALBIN/LISM_WIP/10.png',
      '/ALBIN/LISM_WIP/11.png',
      '/ALBIN/LISM_WIP/12.png',
      '/ALBIN/LISM_WIP/13.png',
      '/ALBIN/LISM_WIP/14.png',
      '/ALBIN/LISM_WIP/15.png',
      '/ALBIN/LISM_WIP/16.png',
    ],
    coveralt: 'Cover artwork for Albin\'s "Love in Slow Motion"',
    description: `Digital illustration for Albin's music single "Love In Slow Motion".`,
    width: 1024,
    height: 1024,
    tools: [
      'Blender 3D',
      'Substance Designer',
      'Substance Painter',
      'Adobe Photoshop',
    ],
  },

  {
    id: nanoid(),
    title: 'A Profound Waste of Time Pages 1 and 2',
    path: 'a-profound-waste-of-time-pages-1-and-2',
    type: 'Editorial Illustration',
    cover: '/images/ILLUSTRATIONS/APWOT/apwot_1.png',
    coveralt:
      "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    description: `Pages 1-2 of an 8-pages spread illustration for A Profound Waste of Time magazine's second issue.`,
    width: 1581,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop', 'Adobe Illustrator'],
  },
  {
    id: nanoid(),
    title: 'A Profound Waste of Time Pages 3 and 4',
    path: 'illustrations',
    type: 'Editorial Illustration',
    cover: '/images/ILLUSTRATIONS/APWOT/apwot_2.png',
    coveralt:
      "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    description: `Pages 3-4 of an 8-pages spread illustration for A Profound Waste of Time magazine's second issue.`,
    width: 1581,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop', 'Adobe Illustrator'],
  },
  {
    id: nanoid(),
    title: 'A Profound Waste of Time Pages 5 and 6',
    path: 'illustrations',
    type: 'Editorial Illustration',
    cover: '/images/ILLUSTRATIONS/APWOT/apwot_3.png',
    coveralt:
      "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    description: `Pages 5-6 of an 8-pages spread illustration for A Profound Waste of Time magazine's second issue.`,
    width: 1581,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop', 'Adobe Illustrator'],
  },
  {
    id: nanoid(),
    title: 'A Profound Waste of Time Pages 7 and 8',
    path: 'illustrations',
    type: 'Editorial Illustration',
    cover: '/images/ILLUSTRATIONS/APWOT/apwot_4.png',
    coveralt:
      "8 pages spread editorial illustration for A Profound Waste of Time's issue 2",
    description: `Pages 7-8 of an 8-pages spread illustration for A Profound Waste of Time magazine's second issue.`,
    width: 1581,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop', 'Adobe Illustrator'],
  },
  {
    id: nanoid(),
    title: 'Illustrated Bookmark',
    path: 'illustrations',
    type: 'Bookmark Artwork',
    cover: '/images/ILLUSTRATIONS/GAMESMASTER/bookmarks.png',
    coveralt: 'Set of bookmark artwork for GamesMaster: A Oral History',
    description:
      'Set of bookmark 3D artworks included in the GameMaster: A Oral History book.',
    width: 1309,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop', 'Adobe Illustrator'],
  },
  {
    id: nanoid(),
    title: 'Breakfast Table',
    path: 'illustrations',
    type: 'Personal Artwork',
    cover: '/images/ILLUSTRATIONS/BREAKFAST/breakfast.png',
    coveralt: 'Personal study for a breakfast scene',
    description: `Lowpoly illustration of breakfast table.`,
    width: 1448,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Abstract Illustration 1',
    path: 'illustrations',
    type: 'Commissioned Abstract Artwork',
    cover: '/images/ILLUSTRATIONS/CHASE/chase.png',
    coveralt: 'Comissioned abstract artwork',
    description: `3D abstract illustration.`,
    width: 1024,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Tropical Scene',
    path: 'illustrations',
    type: 'Digital Artwork',
    cover: '/images/ILLUSTRATIONS/TROPICALSCENE/tropicalscene.png',
    coveralt: 'Personal study of a tropical scene',
    description: '3D illustration of a tropical scene.',
    width: 1600,
    height: 800,
    tools: ['Blender 3D', 'Adobe Photoshop', 'Adobe Illustrator'],
  },
  {
    id: nanoid(),
    title: 'Abstract Comic Strip',
    path: 'illustrations',
    type: 'Digital Comics Strip',
    cover: '/images/ILLUSTRATIONS/STELLA/stella.png',
    coveralt: 'Digital comic strip for Stella',
    description: 'Set of 6 3D illustrations for Stella.',
    width: 1440,
    height: 900,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
  {
    id: nanoid(),
    title: 'Lowpoly Helipcopter',
    path: 'illustrations',
    type: '3D Artwork',
    cover: '/images/ILLUSTRATIONS/HELICOPTER/helicopter.png',
    coveralt: 'Personal study of a helicopter',
    description: 'Stylized lowpoly illustration of a helicopter.',
    width: 1820,
    height: 1024,
    tools: ['Blender 3D', 'Adobe Photoshop'],
  },
];
